service: snap

provider:
  name: aws
  runtime: nodejs8.10

  region: us-east-1
  profile: default
  stage: gamma

  environment:
    CHANNELS_TABLE: ${self:service}.${opt:stage, self:provider.stage}.channels
    # CHANNEL_SESSIONS_TABLE: ${self:service}.${opt:stage, self:provider.stage}.channel-sessions

  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:PutItem
       - dynamodb:GetItem
       - dynamodb:UpdateItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CHANNELS_TABLE}"
    # - Effect: "Allow"
    #   Action:
    #    - dynamodb:Query
    #    - dynamodb:Scan
    #    - dynamodb:PutItem
    #    - dynamodb:GetItem
    #    - dynamodb:UpdateItem
    #   Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CHANNEL_SESSIONS_TABLE}"

functions:
  RetrieveScores:
    handler: source/RetrieveScores.handler
    events:
      - http:
          path: v1/{channelId}/scores
          method: get
          cors: true
  SubmitScore:
    handler: source/SubmitScore.handler
    events:
      - http:
          path: v1/{channelId}/scores
          method: post
          cors: true

resources:
  Resources:
    ChannelsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CHANNELS_TABLE}
        AttributeDefinitions:
          - AttributeName: channelId
            AttributeType: S
        KeySchema:
          - AttributeName: channelId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
      DeletionPolicy: Retain
    # ChannelSessionsTable:
    #   Type: AWS::DynamoDB::Table
    #   Properties:
    #     TableName: ${self:provider.environment.CHANNEL_SESSIONS_TABLE}
    #     AttributeDefinitions:
    #       - AttributeName: channelId-sessionId
    #         AttributeType: S
    #       - AttributeName: score
    #         AttributeType: N
    #     KeySchema:
    #       - AttributeName: channelId-sessionId
    #         KeyType: HASH
    #       - AttributeName: score
    #         KeyType: RANGE
    #     ProvisionedThroughput:
    #       ReadCapacityUnits: 1
    #       WriteCapacityUnits: 1
    #   DeletionPolicy: Retain

package:
  excludeDevDependencies: true
